-- 1. Create Warehouse
CREATE OR REPLACE WAREHOUSE DEMO_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2. Create Database
CREATE OR REPLACE DATABASE DEMO_DB;

-- 3. Create Schema
CREATE OR REPLACE SCHEMA DEMO_DB.PUBLIC;

USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;
USE WAREHOUSE DEMO_WH;
--Create Table 1 — Customers
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID   NUMBER        AUTOINCREMENT,
    FIRST_NAME    STRING,
    LAST_NAME     STRING,
    EMAIL         STRING,
    CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);
--Create Table 2 — Orders
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.ORDERS (
    ORDER_ID      NUMBER        AUTOINCREMENT,
    CUSTOMER_ID   NUMBER,
    ORDER_AMOUNT  NUMBER(10,2),
    ORDER_DATE    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP(),
    STATUS        STRING,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

INSERT INTO DEMO_DB.PUBLIC.CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES
    ('Ravi', 'Kumar', 'ravi.kumar@example.com'),
    ('Anita', 'Sharma', 'anita.sharma@example.com'),
    ('Vikram', 'Reddy', 'vikram.reddy@example.com'),
    ('Sneha', 'Das', 'sneha.das@example.com'),
    ('Rahul', 'Varma', 'rahul.varma@example.com');
INSERT INTO DEMO_DB.PUBLIC.ORDERS (CUSTOMER_ID, ORDER_AMOUNT, STATUS)
VALUES
    (1, 1500.75, 'COMPLETED'),
    (1, 230.50, 'PENDING'),
    (2, 999.99, 'COMPLETED'),
    (3, 450.00, 'CANCELLED'),
    (3, 1299.00, 'COMPLETED'),
    (4, 75.25, 'COMPLETED'),
    (4, 210.00, 'PENDING'),
    (5, 560.40, 'COMPLETED');
