--Create a View (Orders With Customer Details)
CREATE OR REPLACE VIEW DEMO_DB.PUBLIC.VW_CUSTOMER_ORDERS AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    o.ORDER_ID,
    o.ORDER_AMOUNT,
    o.ORDER_DATE,
    o.STATUS
FROM CUSTOMERS c
LEFT JOIN ORDERS o
      ON c.CUSTOMER_ID = o.CUSTOMER_ID;

